set(CPACK_PACKAGE_NAME "OmniStem Studio")
set(CPACK_PACKAGE_VENDOR "OmniStem")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "OmniStem Studio")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Native AI-assisted audio workstation")
set(CPACK_MONOLITHIC_INSTALL ON)

if(WIN32)
    set(CPACK_GENERATOR "NSIS")
    set(CPACK_NSIS_DISPLAY_NAME "OmniStem Studio")
    set(CPACK_NSIS_PACKAGE_NAME "OmniStem Studio")
    set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
    set(CPACK_NSIS_MODIFY_PATH OFF)
    set(CPACK_NSIS_URL_INFO_ABOUT "https://github.com/krishavi85/OmniScript-automation")
else()
    set(CPACK_GENERATOR "ZIP")
endif()

include(CPack)
